name: Build and deploy to DEV
run-name:  ${{ github.actor }} triggered deploy to DEV pipeline

on:
  push:
    branches:
      - dev

jobs:
  setup:
    runs-on: ubuntu-latest
    environment: dev
    outputs:
      docker_build_args: ${{ steps.args.outputs.docker_build_args }}
    steps:
      - uses: actions/checkout@v6

      - name: Read BASE IMAGE VERSION file
        id: getappversion
        run: |
          echo "appversion=$(sed -n 's/^MEDCAT_BASE_IMAGE_VERSION=\(.*\)/\1/p' medcat_versions.yml)" >> "$GITHUB_OUTPUT"

      - id: args
        run: |
          ARGS=""
          ARGS+="--build-arg MEDCAT_BASE_IMAGE_VERSION=${{ steps.getappversion.outputs.appversion }} "
          echo "docker_build_args=$ARGS" >> "$GITHUB_OUTPUT"

  build:
    needs: setup
    uses: HDRUK/github-actions-templates/.github/workflows/docker-build.yaml@main
    with:
      chart_path: chart/gateway-medcat/Chart.yaml
      environment: dev
      docker_build_args: ${{ needs.setup.outputs.docker_build_args }}
    secrets: inherit

  deploy:
    needs: build
    uses: HDRUK/github-actions-templates/.github/workflows/deploy-release.yml@main
    with:
      env: dev
      chart_path: chart/gateway-medcat/Chart.yaml
      git_ref: dev
    secrets: inherit