name: Semantic Release workflow

on:
  push:
    branches:
      - main

jobs:
  semantic:
    uses: HDRUK/github-actions-templates/.github/workflows/semantic.yaml@main
    with:
      chart_path: chart/gateway-medcat/Chart.yaml
    secrets: inherit

  setup-prod:
    runs-on: ubuntu-latest
    environment: prod
    needs: semantic
    outputs:
      docker_build_args: ${{ steps.args.outputs.docker_build_args }}
    steps:
      - name: Read BASE IMAGE VERSION file
        id: getappversion
        run: |
          echo "appversion=$(sed -n 's/^MEDCAT_BASE_IMAGE_VERSION=\(.*\)/\1/p' < medcat_versions.yml)" >> "$GITHUB_OUTPUT"
      
      - id: args
        run: |
          ARGS=""
          ARGS+="--build-arg MEDCAT_BASE_IMAGE_VERSION=${{ steps.getappversion.outputs.appversion }} "
          echo "docker_build_args=$ARGS" >> "$GITHUB_OUTPUT"

  build-prod:
    needs: setup-prod
    uses: HDRUK/github-actions-templates/.github/workflows/docker-build.yaml@main
    with:
      environment: prod
      docker_build_args: ${{ needs.setup-prod.outputs.docker_build_args }}
      chart_path: chart/gateway-medcat/Chart.yaml
    secrets: inherit
